languageCode = "en-us"
title = "Jofukuin"
theme = "default"
baseurl="https://joshuatowner.github.io/jofukin-website/"
canonifyurls = true
disableKinds = ["RSS"]

[markup.goldmark.renderer]
unsafe= true
