languageCode = "en-us"
title = "Jofukin"
theme = "default"
baseurl="https://joshuatowner.github.io/jofukuin-website/"
canonifyurls = true
disableKinds = ["RSS"]

[markup.goldmark.renderer]
unsafe= true
